// auto-generated by nbglsdk.py
#include "nbgl_stubs.h"
#include "nbgl_obj.h"
#include "nbgl_screen.h"
#include "nbgl_touch.h"
#include "nbgl_draw.h"

unsigned long __attribute((section("._nbgl_exported_functions"))) nbgl_exported_functions[] = {
    [_NR_nbgl_redrawObject]                  = (unsigned long) nbgl_redrawObject,
    [_NR_nbgl_refresh]                       = (unsigned long) nbgl_refresh,
    [_NR_nbgl_refreshSpecial]                = (unsigned long) nbgl_refreshSpecial,
    [_NR_nbgl_refreshSpecialWithPostRefresh] = (unsigned long) nbgl_refreshSpecialWithPostRefresh,
    [_NR_nbgl_refreshIsNeeded]               = (unsigned long) nbgl_refreshIsNeeded,
    [_NR_nbgl_refreshReset]                  = (unsigned long) nbgl_refreshReset,
    [_NR_nbgl_objInit]                       = (unsigned long) nbgl_objInit,
    [_NR_nbgl_objAllowDrawing]               = (unsigned long) nbgl_objAllowDrawing,
    [_NR_nbgl_screenSet]                     = (unsigned long) nbgl_screenSet,
    [_NR_nbgl_screenPush]                    = (unsigned long) nbgl_screenPush,
    [_NR_nbgl_screenRedraw]                  = (unsigned long) nbgl_screenRedraw,
    [_NR_nbgl_screenPop]                     = (unsigned long) nbgl_screenPop,
    [_NR_nbgl_screenGetElements]             = (unsigned long) nbgl_screenGetElements,
    [_NR_nbgl_screenGetCurrentStackSize]     = (unsigned long) nbgl_screenGetCurrentStackSize,
    [_NR_nbgl_screenGetAt]                   = (unsigned long) nbgl_screenGetAt,
    [_NR_nbgl_screenUpdateTicker]            = (unsigned long) nbgl_screenUpdateTicker,
    [_NR_nbgl_screenUpdateBackgroundColor]   = (unsigned long) nbgl_screenUpdateBackgroundColor,
    [_NR_nbgl_screenReset]                   = (unsigned long) nbgl_screenReset,
    [_NR_nbgl_screenHandler]                 = (unsigned long) nbgl_screenHandler,
    [_NR_nbgl_objPoolGet]                    = (unsigned long) nbgl_objPoolGet,
    [_NR_nbgl_objPoolGetArray]               = (unsigned long) nbgl_objPoolGetArray,
    [_NR_nbgl_containerPoolGet]              = (unsigned long) nbgl_containerPoolGet,
    [_NR_nbgl_getFont]                       = (unsigned long) nbgl_getFont,
    [_NR_nbgl_getFontHeight]                 = (unsigned long) nbgl_getFontHeight,
    [_NR_nbgl_getFontLineHeight]             = (unsigned long) nbgl_getFontLineHeight,
    [_NR_nbgl_getSingleLineTextWidth]        = (unsigned long) nbgl_getSingleLineTextWidth,
    [_NR_nbgl_getTextHeight]                 = (unsigned long) nbgl_getTextHeight,
    [_NR_nbgl_getTextHeightInWidth]          = (unsigned long) nbgl_getTextHeightInWidth,
    [_NR_nbgl_getTextNbLinesInWidth]         = (unsigned long) nbgl_getTextNbLinesInWidth,
    [_NR_nbgl_getTextWidth]                  = (unsigned long) nbgl_getTextWidth,
    [_NR_nbgl_getTextMaxLenInNbLines]        = (unsigned long) nbgl_getTextMaxLenInNbLines,
    [_NR_nbgl_textReduceOnNbLines]           = (unsigned long) nbgl_textReduceOnNbLines,
    [_NR_nbgl_textWrapOnNbLines]             = (unsigned long) nbgl_textWrapOnNbLines,
    [_NR_nbgl_refreshUnicodeFont]            = (unsigned long) nbgl_refreshUnicodeFont,
    [_NR_nbgl_setLanguagePack]               = (unsigned long) nbgl_setLanguagePack,
    [_NR_nbgl_touchHandler]                  = (unsigned long) nbgl_touchHandler,
    [_NR_nbgl_touchGetTouchDuration]         = (unsigned long) nbgl_touchGetTouchDuration,
    [_NR_nbgl_touchGetTouchedPosition]       = (unsigned long) nbgl_touchGetTouchedPosition,
    [_NR_nbgl_drawText]                      = (unsigned long) nbgl_drawText,
};
