# Emit a one-line C file defining the Absolution state-prefix size.
#
# Run as a build step (cmake -P) with:
#   -D FUZZER_C=<generated fuzzer.c>  -D OUT=<fuzz_prefix_size.c>
#
# The size is only known once Absolution has generated the fuzzer, so it cannot be
# a configure-time value. Emitting it as data in one generated translation unit
# means a size change recompiles one file and relinks, rather than invalidating
# every compile line as a -D macro would.

if(NOT FUZZER_C OR NOT OUT)
  message(FATAL_ERROR "EmitPrefixSize.cmake: FUZZER_C and OUT are both required")
endif()

if(NOT EXISTS "${FUZZER_C}")
  message(FATAL_ERROR "EmitPrefixSize.cmake: generated fuzzer not found: ${FUZZER_C}")
endif()

# Absolution emits `#define ABSOLUTION_GLOBALS_SIZE <n>` into fuzzer.c. Newer
# versions moved it to a companion header as ABSOLUTION_STATE_PREFIX_SIZE; accept
# either so a version bump does not need this file changed in the same commit.
file(STRINGS "${FUZZER_C}" _size_line
     REGEX "^#define (ABSOLUTION_GLOBALS_SIZE|ABSOLUTION_STATE_PREFIX_SIZE) +[0-9]+u?")

if(NOT _size_line)
  get_filename_component(_dir "${FUZZER_C}" DIRECTORY)
  if(EXISTS "${_dir}/fuzzer.h")
    file(STRINGS "${_dir}/fuzzer.h" _size_line
         REGEX "^#define ABSOLUTION_STATE_PREFIX_SIZE +[0-9]+u?")
  endif()
endif()

if(NOT _size_line)
  message(FATAL_ERROR
    "EmitPrefixSize.cmake: no prefix-size define found in ${FUZZER_C}.\n"
    "The prefix-aware mutator would silently degrade to flat-byte mutation over\n"
    "structured state, so this is fatal rather than defaulted to zero.")
endif()

list(GET _size_line 0 _size_line)
string(REGEX MATCH "[0-9]+" _prefix_size "${_size_line}")

if(NOT _prefix_size OR _prefix_size EQUAL 0)
  message(FATAL_ERROR "EmitPrefixSize.cmake: parsed a zero/empty prefix size from '${_size_line}'")
endif()

set(_content "/* Generated by EmitPrefixSize.cmake -- do not edit.
 *
 * Absolution's state-prefix size, as data rather than a compile-time macro, so
 * that only this translation unit depends on it. Declared in fuzz_defs.h.
 */
#include <stddef.h>

const size_t fuzz_absolution_prefix_size = ${_prefix_size};
")

# Write only on change so an unchanged size does not touch the file and trigger a
# needless recompile and relink.
set(_existing "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _existing)
endif()
if(NOT _existing STREQUAL _content)
  file(WRITE "${OUT}" "${_content}")
  message(STATUS "prefix size: ${_prefix_size} -> ${OUT}")
endif()
