/*****************************************************************************
 *   (c) 2026 Ledger SAS.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *****************************************************************************/

#pragma once

/**
 * @file identity.h
 * @brief Register / Edit Contact Name / Edit Scope / Edit Identifier
 *
 * An Identity is a contact identified by a name, an IDENTIFIER (blockchain
 * address or public key, up to 80 bytes), an optional SCOPE (context
 * string, e.g. "Ethereum"), and a derivation path used to derive the HMAC key
 * for the Proof of Registration.
 *
 * Active under HAVE_ADDRESS_BOOK (no sub-flag required).
 */

#if defined(HAVE_ADDRESS_BOOK)

/* Includes ------------------------------------------------------------------*/
#include "os_types.h"
#include "address_book.h"
#include "bip32.h"

/* Exported defines   --------------------------------------------------------*/
#define TYPE_REGISTER_IDENTITY 0x11
#define TYPE_EDIT_CONTACT_NAME 0x12
#define TYPE_EDIT_IDENTIFIER   0x15
#define TYPE_EDIT_SCOPE        0x16

/* Exported defines (unconditional — plain numeric constants) ----------------*/
#define GID_SIZE          32  ///< 32-byte random group ID generated by the device
#define GROUP_HANDLE_SIZE 64  ///< group_handle = gid(32) | MAC(K_group, gid)(32)

#define CONTACT_NAME_LENGTH   33  ///< max 32 printable chars + null terminator
#define SCOPE_LENGTH          33  ///< max 32 printable chars + null terminator
#define IDENTIFIER_MAX_LENGTH 80  ///< blockchain address or public key, raw bytes

/* Exported types, structures, unions ----------------------------------------*/

/**
 * @brief Data extracted from a Register Identity TLV payload.
 *
 * @note gid is device-generated at registration and included in both HMACs;
 *       it is never displayed to the user.
 */
typedef struct {
    uint8_t             gid[GID_SIZE];  ///< Device-generated group ID (first 32B of group_handle)
    char                contact_name[CONTACT_NAME_LENGTH];
    char                scope[SCOPE_LENGTH];
    uint8_t             identifier[IDENTIFIER_MAX_LENGTH];
    uint8_t             identifier_len;
    path_bip32_t        bip32_path;  ///< Used to derive the HMAC key for the Proof of Registration
    blockchain_family_e blockchain_family;
    uint64_t            chain_id;  ///< Mandatory when blockchain_family == FAMILY_ETHEREUM
} identity_t;

/**
 * @brief Data extracted from an Edit Identifier TLV payload.
 */
typedef struct {
    identity_t identity;                                    ///< Updated identity (identifier = new)
    uint8_t    previous_identifier[IDENTIFIER_MAX_LENGTH];  ///< Identifier being replaced
    uint8_t    previous_identifier_len;                     ///< Length of the previous identifier
} edit_identifier_t;

/**
 * @brief Data extracted from an Edit Contact Name TLV payload.
 */
typedef struct {
    uint8_t      gid[GID_SIZE];                      ///< Group ID extracted from group_handle
    char         contact_name[CONTACT_NAME_LENGTH];  ///< New contact name
    char         previous_contact_name[CONTACT_NAME_LENGTH];  ///< Previous contact name
    path_bip32_t bip32_path;                                  ///< BIP32 derivation path
} edit_contact_name_t;

/**
 * @brief Data extracted from an Edit Scope Name TLV payload.
 *
 * Changes the scope of an existing contact while keeping the same
 * contact_name and identifier.
 */
typedef struct {
    identity_t identity;                      ///< New identity (scope = new)
    char       previous_scope[SCOPE_LENGTH];  ///< Scope being replaced
} edit_scope_t;

/* Exported functions prototypes --------------------------------------------- */
bolos_err_t register_identity(uint8_t *buffer_in, size_t buffer_in_length);
bolos_err_t edit_contact_name(uint8_t *buffer_in, size_t buffer_in_length);
bolos_err_t edit_identifier(uint8_t *buffer_in, size_t buffer_in_length);
bolos_err_t edit_scope(uint8_t *buffer_in, size_t buffer_in_length);

#endif  // HAVE_ADDRESS_BOOK
