# Ported from the apex_p block of Makefile.defines.
set(LEDGER_TARGET_DEFS
    HAVE_BAGL_FONT_NANODISPLAY_SEMIBOLD_24PX
    HAVE_BAGL_FONT_NANOTEXT_BOLD_18PX
    HAVE_BAGL_FONT_NANOTEXT_MEDIUM_18PX
    HAVE_INAPP_BLE_PAIRING
    HAVE_NBGL
    HAVE_SE_EINK_DISPLAY
    HAVE_SE_TOUCH
    NBGL_PAGE
    NBGL_USE_CASE
    SCREEN_SIZE_WALLET
    TARGET="apex_p"
    TARGET_NAME="TARGET_APEX_P"
)
