# Ported from the flex block of Makefile.defines.
set(LEDGER_TARGET_DEFS
    HAVE_BAGL_FONT_INTER_MEDIUM_36PX
    HAVE_BAGL_FONT_INTER_REGULAR_28PX
    HAVE_BAGL_FONT_INTER_SEMIBOLD_28PX
    HAVE_INAPP_BLE_PAIRING
    HAVE_NBGL
    HAVE_PIEZO_SOUND
    HAVE_SE_EINK_DISPLAY
    HAVE_SE_TOUCH
    NBGL_PAGE
    NBGL_USE_CASE
    SCREEN_SIZE_WALLET
    TARGET="flex"
    TARGET_NAME="TARGET_FLEX"
)
