# Ported from the stax block of Makefile.defines.
set(LEDGER_TARGET_DEFS
    HAVE_BAGL_FONT_INTER_MEDIUM_32PX
    HAVE_BAGL_FONT_INTER_REGULAR_24PX
    HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX
    HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX_1BPP
    HAVE_INAPP_BLE_PAIRING
    HAVE_NBGL
    HAVE_PIEZO_SOUND
    HAVE_SE_EINK_DISPLAY
    HAVE_SE_TOUCH
    NBGL_PAGE
    NBGL_USE_CASE
    SCREEN_SIZE_WALLET
    TARGET="stax"
    TARGET_NAME="TARGET_STAX"
)
