name: Build clang runtime builtins
on:
  workflow_dispatch:
  # TODO: remove this next line before merging!
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - core: cortex-m3
            se: st33
          - core: cortex-m35p+nodsp
            se: st33k1

    steps:
      - uses: actions/checkout@v4
        with:
          # TODO: remove this next line before merging!
          ref: feat/apa/clangrt
          sparse-checkout: |
            tools/build_clangrt_builtins.sh
          sparse-checkout-cone-mode: false

      - run: ./tools/build_clangrt_builtins.sh -t ${{ matrix.target.core }} -o artifact/arch/${{ matrix.target.se }}/lib

      - uses: actions/upload-artifact@v4
        with:
          name: arch-${{ matrix.target.se }}
          path: artifact/

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: arch
          pattern: arch-*
          delete-merged: true
