name: Build clang runtime builtins
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      target_sdk_branch:
        type: string
        required: false
        default: 'master'
      create_pr:
        type: boolean
        required: false
        default: false

env:
  GIT_USER_EMAIL: 'ledger@github.com'
  GIT_USER_NAME: 'SDKLibsUpdaterGithub'
  UPDATE_BRANCH: 'sdk_libs_update'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - core: cortex-m3
            se: st33
          - core: cortex-m35p+nodsp
            se: st33k1

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools/build_clangrt_builtins.sh
            tools/build_newlib.sh
          sparse-checkout-cone-mode: false

      - run: ./tools/build_clangrt_builtins.sh -t ${{ matrix.target.core }} -o artifact/arch/${{ matrix.target.se }}/lib

      - run: ./tools/build_newlib.sh -t ${{ matrix.target.core }} -o artifact/arch/${{ matrix.target.se }}/lib

      - uses: actions/upload-artifact@v4
        with:
          name: arch-${{ matrix.target.se }}
          path: artifact/

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: arch
          pattern: arch-*
          delete-merged: true

  pr_create:
    needs: merge
    runs-on: ubuntu-latest
    if: ${{ success() && inputs.create_pr }}
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # by default the action uses fetch-depth = 1, which creates
          # shallow repositories from which we can't push
          fetch-depth: 0
          ref: ${{ inputs.target_sdk_branch }}

      - name: Download Binaries artifact
        uses: actions/download-artifact@v4
        with:
          name: arch

      - name: PR creation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: ${{ inputs.target_sdk_branch }}
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"
          git switch --create "$UPDATE_BRANCH"
          git add -A .
          git commit -m 'Updating static SDK libraries'
          git push -u origin "$UPDATE_BRANCH"
          gh pr create -B "$TARGET_BRANCH" --title '[SDK_LIBS_UPDATE] Updating static SDK libraries' --body 'Created by Github workflow "${{ github.workflow }}", job "${{ github.job }}", run "${{ github.run_id }}".'
