name: Build all Rust apps

on:
  workflow_dispatch:
  pull_request:

jobs:
    display_branch:
        name: Display branch
        runs-on: ubuntu-latest
        steps:
            - name: Display branch
              run: |
                echo "Branch:" ${{ github.ref }}
                echo "Head ref:" ${{ github.head_ref }}
    test_build_rust:
        name: Build all Rust apps with the reusable workflow
        uses: LedgerHQ/ledger-device-rust-sdk/.github/workflows/reusable_build_all_apps.yml@master
        with:
            c_sdk_branch: '${{ github.head_ref }}'
            c_sdk_repo: '${{ github.repository }}'
