name: Build all C apps on latest SDK

on:
  workflow_dispatch:
    inputs:
      sdk_branch:
        type: string
        required: false
        default: origin/master
  pull_request:

jobs:

  build_all_applications:
    name: Build all the C applications on all the devices
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build_several.yml@add/reusable_workflow_to_build_all_apps
    with:
      sdk: c
      sdk_reference: ${{ inputs.sdk_branch }}
      devices: all
      exclude_apps: app-avalanche
