name: Documentation generation & update

on:
  push:
    tags:
      - '*'
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  generate:
    name: Generate the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen doxygen-doc graphviz
      - name: Generate the documentation
        run: mkdir -p build && doxygen doc/Doxyfile
      - name: Upload documentation bundle
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: build/doc/html/

  deploy:
    name: Deploy the documentation on Github pages
    runs-on: ubuntu-latest
    needs: generate
    if: github.event_name == 'push'  && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download documentation bundle
        uses: actions/download-artifact@v3
      - name: Deploy documentation on pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/
